version: '3.8'

services:
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=your-username
      - POSTGRES_PASSWORD=your-password
      - POSTGRES_DB=your-database-name
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
